FROM nginx:alpine

RUN apk add --no-cache openssl

COPY ./frontend /usr/share/nginx/html
COPY ./infra/nginx/nginx.conf /etc/nginx/conf.d/default.conf

RUN mkdir -p /etc/nginx/certs && \
    openssl req -x509 -nodes -days 365 \
      -subj "/CN=localhost" \
      -newkey rsa:2048 \
      -keyout /etc/nginx/certs/localhost.key \
      -out /etc/nginx/certs/localhost.crt

EXPOSE 80 443

