listening-port=3478
tls-listening-port=5349
listening-ip=0.0.0.0

external-ip=45.10.43.191

fingerprint
# lt-cred-mech
realm=nomax.local

# Для интеграции с Python бэкендом лучше использовать secret, а не статических юзеров
#static-auth-secret=your-super-secret-turn-key

# Если нужны статические пользователи для тестов:
user=nomax:nomaxpass

total-quota=100
stale-nonce=600
no-loopback-peers
no-multicast-peers
no-cli
min-port=10000
max-port=20000